export type {
  ActionField,
  ActionFilter,
  ActionRequest,
  DeleteRequest,
  ActionResponse,
} from "@/rest-api/interfaces/action";
export type {
  Aggregate,
  AggregateType,
  BaseFilter,
  Filter,
  FilterOperator,
  FilterType,
  Gate,
  Include,
  Instruction,
  InstructionField,
  NestedFilter,
  Scope,
  ScopeParameter,
  SearchRequest,
  SearchText,
  Select,
  Sort,
  SortDirection,
  SearchResponse,
} from "@/rest-api/interfaces/search";

export type {
  MutateRequest,
  OperationType,
  AttachRelation,
  BaseMutationOperation,
  CreateOperation,
  CreateRelation,
  DetachRelation,
  MutateResponse,
  MutationOperation,
  RelationOperation,
  SyncRelation,
  ToggleRelation,
  UpdateOperation,
} from "@/rest-api/interfaces/mutate";
